document.write( '<div class=\"tisirnet\" style=\"margin-bottom: 50px;\">\n' );
document.write( '  <link href=\"https://bit.ly/3KtRIeN\" rel=\"stylesheet\" />\n' );
document.write( '  <details>\n' );
document.write( '    <summary>إتخاذ إجراء</summary>\n' );
document.write( '    <div class=\"$(function(AT-FAQ)\">\n' );
document.write( '      <div\n' );
document.write( '        class=\"coderim\"\n' );
document.write( '        style=\"border-radius: 4px; border: 1px solid rgb(230, 230, 230); text-align: right; width: 100%;\"\n' );
document.write( '      >\n' );
document.write( '        <ul style=\"text-align: right;\"></ul>\n' );
document.write( '        <ul style=\"text-align: right;\">\n' );
document.write( '          <li>\n' );
document.write( '            عذراً: لقراءة المقال، إذا لم يظهر، يرجى الضغط على زر \"إقرأ على\n' );
document.write( '            الموقع الرسمي\" أدناه.\n' );
document.write( '          </li>\n' );
document.write( '          <li>\n' );
document.write( '            إرسال طلب إزالة المحتوى بسبب إنتهاك حقوق الطبع والنشر يرجى النقر على\n' );
document.write( '            <b><a href=\"https://forms.gle/rbq7FpjtQYRxaF1R8\">إتصال بنا</a></b\n' );
document.write( '            >.<br />\n' );
document.write( '          </li>\n' );
document.write( '        </ul>\n' );
document.write( '        <ul style=\"text-align: right;\"></ul>\n' );
document.write( '        <div class=\"redchof\">\n' );
document.write( '          <p style=\"text-align: center;\">\n' );
document.write( '            <button\n' );
document.write( '              style=\"border-radius: 4px; border: 1px solid rgb(255, 255, 255); padding: 0px; text-align: center; width: 98%;\"\n' );
document.write( '            >\n' );
document.write( '              <a href=\"[source_link]\"\n' );
document.write( '                ><span\n' );
document.write( '                  style=\"background: rgb(0, 140, 186) none repeat scroll 0% 0%; border-radius: 4px; color: white; display: block; font-size: 18px; padding: 5px; width: auto;\"\n' );
document.write( '                  >إقرأ على الموقع الرسمي</span\n' );
document.write( '                ></a\n' );
document.write( '              >\n' );
document.write( '            </button>\n' );
document.write( '          </p>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '  </details>\n' );
document.write( '</div>' );
