document.write( '<div class=\"tisirnet\" style=\"margin-bottom: 50px;\">\n' );
document.write( '  <link href=\"https://bit.ly/3KtRIeN\" rel=\"stylesheet\" />\n' );
document.write( '  <details>\n' );
document.write( '    <summary>≈ Œ«– ≈Ã—«¡</summary>\n' );
document.write( '    <div class=\"$(function(AT-FAQ)\">\n' );
document.write( '      <div\n' );
document.write( '        class=\"coderim\"\n' );
document.write( '        style=\"border-radius: 4px; border: 1px solid rgb(230, 230, 230); text-align: right; width: 100%;\"\n' );
document.write( '      >\n' );
document.write( '        <ul style=\"text-align: right;\"></ul>\n' );
document.write( '        <ul style=\"text-align: right;\">\n' );
document.write( '          <li>\n' );
document.write( '            ⁄–—«: ·ﬁ—«¡… «·„ﬁ«·° ≈–« ·„ ÌŸÂ—° Ì—ÃÏ «·÷€ÿ ⁄·Ï “— \"≈ﬁ—√ ⁄·Ï\n' );
document.write( '            «·„Êﬁ⁄ «·—”„Ì\" √œ‰«Â.\n' );
document.write( '          </li>\n' );
document.write( '          <li>\n' );
document.write( '            ≈—”«· ÿ·» ≈“«·… «·„Õ ÊÏ »”»» ≈‰ Â«ﬂ ÕﬁÊﬁ «·ÿ»⁄ Ê«·‰‘— Ì—ÃÏ «·‰ﬁ— ⁄·Ï\n' );
document.write( '            <b><a href=\"https://forms.gle/rbq7FpjtQYRxaF1R8\">≈ ’«· »‰«</a></b\n' );
document.write( '            >.<br />\n' );
document.write( '          </li>\n' );
document.write( '        </ul>\n' );
document.write( '        <ul style=\"text-align: right;\"></ul>\n' );
document.write( '        <div class=\"redchof\">\n' );
document.write( '          <p style=\"text-align: center;\">\n' );
document.write( '            <button\n' );
document.write( '              style=\"border-radius: 4px; border: 1px solid rgb(255, 255, 255); padding: 0px; text-align: center; width: 98%;\"\n' );
document.write( '            >\n' );
document.write( '              <a href=\"[source_link]\"\n' );
document.write( '                ><span\n' );
document.write( '                  style=\"background: rgb(0, 140, 186) none repeat scroll 0% 0%; border-radius: 4px; color: white; display: block; font-size: 18px; padding: 5px; width: auto;\"\n' );
document.write( '                  >≈ﬁ—√ ⁄·Ï «·„Êﬁ⁄ «·—”„Ì</span\n' );
document.write( '                ></a\n' );
document.write( '              >\n' );
document.write( '            </button>\n' );
document.write( '          </p>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '  </details>\n' );
document.write( '</div>' );
